bizlink/bizlink/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("core/", include("core.urls")),
    path("userauth/", include("userauth.urls")),
    path("chat/", include("chat.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

bizlink/chat/urls.py
from django.urls import path

from . import views

app_name = "chat"

urlpatterns = [
    path("", views.chat, name="chat"),
    path("chatroom/<chatGroupId>/", views.chatroom, name="chatroom"),
    path("get_or_create_chatroom/<username>/", views.get_or_create_chatroom, name="get_or_create_chatroom"),
    path('unread-count/<chatGroupId>/', views.unread_message_count, name='unread_message_count'),
]

bizlink/core/urls.py
from django.urls import path

from . import views

app_name = "core"

urlpatterns = [

    # Path for both

    ## Account
    path("account/", views.account, name="account"),
    path("account/notification/", views.notification, name="notification"),
    
    ## Wishlist
    path("wishlist/", views.wishlist, name="wishlist"),

    # Path for the owner

    ## Admin
    path("owner/home/admin/", views.admin, name="admin"),
    path("owner/home/admin/update_shop/", views.update_shop, name="update_shop"),
    path("owner/home/admin/create_feature/", views.create_feature, name="create_feature"),
    path('owner/home/admin/add_featured_product/', views.add_featured_product, name='add_featured_product'),
    path('owner/home/admin/delete_featured_product/', views.delete_featured_product, name="delete_featured_product"),
    path('owner/home/admin/add_new_arrival/', views.add_new_arrival, name='add_new_arrival'),
    path('owner/home/admin/delete_new_arrival/', views.delete_new_arrival, name="delete_new_arrival"),
    path('owner/home/admin/delete_feature/', views.delete_feature, name="delete_feature"),

    ## Category
    path("owner/home/categories/", views.category, name="category"),
    path("owner/home/category/<categoryId>/", views.category_detail, name="category_detail"),

    ## Product
    path("owner/home/products/", views.product, name="product"),
    path("owner/home/product/<productId>/", views.product_detail, name="product_detail"),
    path('owner/home/product/apply-discount/<productId>/', views.apply_discount, name='apply_discount'),
    path('owner/home/product/delete-discount/<productId>/', views.delete_discount, name='delete_discount'),
    path("owner/home/products/tag/<slug:tag_slug>/", views.tag, name="tag"),

    ## Factory
    path("owner/factory/", views.factory, name="factory"),
    path("owner/home/inventory/get_updated_stock/", views.get_updated_stock, name="get_updated_stock"),

    ## Inventory
    path("owner/home/inventory/", views.inventory, name="inventory"),
    path("owner/home/inventory/delete_product/", views.delete_product, name="delete_product"),
    path("owner/home/inventory/add_stock/", views.add_stock, name="add_stock"),
    path("owner/home/inventory/sell_stock/", views.sell_stock, name="sell_stock"),
    path("owner/home/inventory/undo_last_transaction/", views.undo_last_transaction, name="undo_last_transaction"),
    path("owner/home/inventory/delete_category/", views.delete_category, name="delete_category"),
    path("owner/home/inventory/delete_transaction_log/", views.delete_transaction_log, name="delete_transaction_log"),
    path("owner/home/inventory/delete_more_product_image/", views.delete_more_product_image, name="delete_more_product_image"),
    path("owner/home/inventory/delete_more_product_video/", views.delete_more_product_video, name="delete_more_product_video"),
    path("owner/home/inventory/delete_product_video/", views.delete_product_video, name="delete_product_video"),
    path("owner/home/inventory/update_product_info/<productId>", views.update_product_info, name="update_product_info"),
    path("owner/home/inventory/category_inventory_view/<categoryId>/", views.category_inventory_view, name="category_inventory_view"),
    path("owner/home/inventory/update_category_info/<categoryId>", views.update_category_info, name="update_category_info"),
    path("owner/home/inventory/delete_category_image/", views.delete_category_image, name="delete_category_image"),

    ## Search
    path("owner/home/search/", views.search_owner, name="search_owner"),
    path("owner/home/search/filter_searched_product/", views.filter_searched_product, name="filter_searched_product"),

    ## Shop
    path("owner/shop/", views.owner_shop, name="owner_shop"),
    path("owner/shop/add-to-wishlist/", views.add_to_wishlist, name="add-to-wishlist"),

    # Path for the Customer Pages
    
    path("customer/home/", views.customer_home, name="customer_home"),
    path("customer/shop/", views.shop_collection, name="shop_collection"),
    path("customer/home/shops/search", views.search_customer, name="search_customer"),
    path("customer/shops/visit_shop/<shopId>/", views.visit_shop, name="visit_shop"),
]

bizlink/core/models.py
from django.db import models

# Create your models here.

bizlink/core/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
import json
from django.contrib import messages
from django.db.models import Q
from taggit.models import Tag
from django.template.loader import render_to_string
from django.views.decorators.cache import never_cache
from datetime import datetime
from django.utils.dateparse import parse_datetime

from shop.forms import EditShop, CreateFeature, EditProductForm, MoreProductImageForm, MoreProductVideoForm, EditCategoryForm, CreateCategoryForm, CreateProductForm
from userauth.forms import SocialMediaForm

from shop.models import Shop, Category, Product, DiscountedProduct, MoreProductImage, MoreProductVideo, Wishlist, Feature, FeaturedProduct, NewArrival, TransactionLog, ProductVideo
from userauth.models import Profile, SocialMedia, Notification

######################################################################################
###################################### Customer ######################################
######################################################################################

""" Home """

@never_cache
def customer_home(request):

    return render(request, "core/customer/home.html")

""" Shop """

def shop_collection(request):

    shops = Shop.objects.all().order_by("name")

    return render(request, "core/customer/shop.html", {
        'shops': shops
    })

def search_customer(request):
    query = request.GET.get('q', '')

    # Initial search based on query
    shops = Shop.objects.all().order_by("-created_at")

    # Handle cases where query is invalid or trivial
    if query.strip() in ['.', '', '*']:
        shops = shops.none()

    # Handle invalid or trivial queries
    else:
        if query:

            keywords = [keyword.strip() for keyword in query.split(',') if keyword.strip()]
            query_filter = Q()

            for keyword in keywords:
                query_filter |= Q(name__icontains=keyword) | Q(description__icontains=keyword) | Q(address__icontains=keyword)

            shops = shops.filter(query_filter)
    
    request.session['searched_shops'] = list(shops.values_list('shopId', flat=True))
    
    return render(request, "core/customer/shop.html", {
        'shops': shops,
        'query': query,
    })

@never_cache
def visit_shop(request, shopId):
    user = request.user
    request.session['current_shop_id'] = shopId
    
    shop = Shop.objects.get(shopId=shopId)

    # Fetch the same data as before
    social_media = SocialMedia.objects.filter(created_by=shop.created_by)
    features = Feature.objects.filter(created_by=shop.created_by)
    featured_products = FeaturedProduct.objects.filter(shop=shop)
    new_arrivals = NewArrival.objects.filter(shop=shop)
    discounted_products = DiscountedProduct.objects.filter(shop=shop)
    wishlist_items = Wishlist.objects.filter(created_by=user).values_list('product__productId', flat=True)

    return render(request, "core/owner/shop.html", {
        'shop': shop,
        'social_media': social_media,
        'features': features,
        'featured_products': featured_products,
        'new_arrivals': new_arrivals,
        'discounted_products': discounted_products,
        'wishlist_items': wishlist_items,
    })

######################################################################################
####################################### Owner ########################################
######################################################################################

""" Search """

def search_owner(request):
    query = request.GET.get('q', '')
    user = request.user

    # Initial search based on query
    products = Product.objects.filter(created_by=user).select_related('shop').order_by("-created_at")

    # Handle cases where query is invalid or trivial
    if query.strip() in ['.', '', '*']:
        products = products.none()

    # Handle invalid or trivial queries
    else:
        if query:

            keywords = [keyword.strip() for keyword in query.split(',') if keyword.strip()]
            query_filter = Q()

            for keyword in keywords:
                query_filter |= Q(name__icontains=keyword) | Q(description__icontains=keyword)

            products = products.filter(query_filter)
    
    request.session['searched_products'] = list(products.values_list('productId', flat=True))
    
    return render(request, "core/owner/search.html", {
        'products': products,
        'query': query,
    })

def filter_searched_product(request):
    categories = request.GET.getlist("category[]")
    shops = request.GET.getlist("shop[]")
    
    # Get min and max price from the request
    min_price = request.GET.get("min_price")
    max_price = request.GET.get("max_price")

    # Get the searched product IDs from the session
    searched_product_ids = request.session.get('searched_products', [])
    
    # Use productId for filtering
    products = Product.objects.filter(productId__in=searched_product_ids).distinct()

    if len(categories) > 0:
        products = products.filter(category__categoryId__in=categories).distinct()

    if len(shops) > 0:
        products = products.filter(shop__shopId__in=shops).distinct()

    # Filter by price range if provided
    if min_price:
        products = products.filter(price__gte=min_price)
    if max_price:
        products = products.filter(price__lte=max_price)

    data = render_to_string("core/owner/filtered-product.html", {
        'products': products,
    })

    return JsonResponse({
        "data": data,
    })

""" Shop """

@never_cache
def owner_shop(request):
    user = request.user
    shop = None

    if user.user_type == 'business_owner':  
    # Owner: Fetch the shop based on the logged-in user
        try:
            shop = Shop.objects.get(created_by=user)
        except Shop.DoesNotExist:
            messages.error(request, "You don't have a shop registered.")

    elif user.user_type == 'customer':
        # Customer: Use session-stored shopId to view a shop
        shopId = request.session.get('current_shop_id')
        if shopId:
            shop = get_object_or_404(Shop, shopId=shopId)
        else:
            messages.error(request, "No products available.")

    social_media = SocialMedia.objects.filter(created_by=shop.created_by)
    categories = Category.objects.filter(created_by=shop.created_by)
    features = Feature.objects.filter(created_by=shop.created_by)
    featured_products = FeaturedProduct.objects.filter(created_by=shop.created_by)
    new_arrivals = NewArrival.objects.filter(created_by=shop.created_by)
    discounted_products = DiscountedProduct.objects.filter(created_by=shop.created_by, shop=shop)
    wishlist_items = Wishlist.objects.filter(created_by=user).values_list('product__productId', flat=True)

    return render(request, "core/owner/shop.html", {
        'user': user,
        'shop': shop,
        'social_media': social_media,
        'features': features,
        'featured_products': featured_products,
        'new_arrivals': new_arrivals,
        'discounted_products': discounted_products,
        'categories': categories,
        'wishlist_items': wishlist_items,
    })

""" Admin """

def admin(request):
    user = request.user
    products = Product.objects.filter(created_by=user)
    shop = Shop.objects.get(created_by=user)
    features = Feature.objects.filter(created_by=user, shop=shop)
    create_feature_form = CreateFeature()
    featured_products = FeaturedProduct.objects.filter(created_by=user)
    new_arrivals = NewArrival.objects.filter(created_by=user)
    social_media_form = SocialMediaForm()

    return render(request, "core/owner/admin.html", {
        'shop': shop,
        'features': features,
        'products': products,
        'create_feature_form': create_feature_form,
        'featured_products': featured_products,
        'new_arrivals': new_arrivals,
        'social_media_form': social_media_form,
    })

def update_shop(request):
    user = request.user
    shop = Shop.objects.get(created_by=user)  

    if request.method == 'POST':
        form = EditShop(request.POST, request.FILES, instance=shop)

        if form.is_valid():
            form.save()

            return redirect("core:owner_shop") 
        
        else: 
            print(form.errors)

    else:
        form = EditShop(instance=shop)

    return render(request, 'core/owner/admin.html', {
        'form': form,
        'shop': shop
    })


def create_feature(request):
    user = request.user
    shop = get_object_or_404(Shop, created_by=user)
    features = Feature.objects.filter(created_by=user)

    if request.method == "POST":
        form = CreateFeature(request.POST, request.FILES)

        if form.is_valid():
            # Check if the feature limit is reached
            if features.count() >= 5:  # Changed to >= to enforce the limit
                messages.error(request, "Feature limit reached. You can only create up to 5 features.")
                return redirect("core:admin")

            feature = form.save(commit=False)
            feature.shop = shop
            feature.created_by = request.user
            feature.save()
            messages.success(request, "Feature created successfully!")
            return redirect("core:admin")  # Redirect after successful creation

    else:
        form = CreateFeature()

    return render(request, "core/owner/shop.html", {
        'shop': shop,
        'features': features,
        'form': form
    })

def delete_feature(request):
    try:
        # Load the JSON data from the request body
        data = json.loads(request.body)
        feature_ids = data.get('feature_ids', [])  # Get the list of feature IDs

        if not feature_ids:
            return JsonResponse({'success': False, 'message': 'No features selected.'})

        # Get the shop owned by the current user

bizlink/shop/views.py
from django.shortcuts import render

# Create your views here.

bizlink/templates/core/customer/home.html
{% extends "core/base.html" %}

{% load static %}

{% block title %}
Home
{% endblock %}

{% block content %}

<!-- ========================================================================================= -->
<!------------------------------------- Home Intro Section ------------------------------------->
<!-- ========================================================================================= -->

<section class="home_intro_section">
    <div class="container">
        <div class="intro-section-box">

            <div class="detail">
                <h1>Welcome to Sammy!</h1>
                <p>At Sammy, we connect you to a wide variety of shops opened by local business owners. Discover an extensive range of options right at your fingertips.</p>
            </div>

            <div class="image">
                <img src="{% static 'img/customer_intro.png' %}" alt="customer-intro image">
            </div>

        </div>
    </div>
</section>

{% endblock %}

bizlink/templates/core/customer/shop.html
{% extends "core/base.html" %}

{% load static %}

{% block title %}
Shops
{% endblock %}

{% block content %}
<section class="shop-intro-section">
    <div class="container">
        <h1>Shops</h1>

        <div class="search-box">
            <div class="search">
                <form
                class="d-flex" role="search" method="GET" action="{% url 'core:search_customer' %}">
                <input
                    class="form-control me-2 search-bar"
                    type="search"
                    placeholder="Search here"
                    aria-label="Search"
                    name="q"
                    value="{{ query }}"
                />
                <button
                    class="btn btn-outline-success search-btn"
                    type="submit"
                >
                    Search
                </button>
                </form>
            </div>
        </div>

        <div class="shop-collection">

            {% if shops %}

                <p class="shop-tally">As of now, we have 

                    {% if shops.count  == 1 %}
                        1 Shop
                    {% else %}
                        {{ shops.count  }} shops
                    {% endif %}

                </p>

                    <div class="shop-collection-box">

                        {% for shop in shops %}

                            <div class="shop-box">

                                <div class="shop-image-column">

                                    <div class="shop-image">
                                       <img src="{{ shop.image.url }}" alt="{{ shop.name }} image">
                                    </div>
                                    
                                    <p>
                                        {% if shop.shop_categories.count  == 1 %}
                                            1 Category
                                        {% else %}
                                            {{ shop.shop_categories.count }} categories
                                        {% endif %}
                                    </p>

                                </div>

                                <div class="shop-detail">
                                    <p>Since {{ shop.created_at|date:"M j, Y" }}</p>
                                    <h3>{{ shop.name }}</h3>
                                    <p>{{ shop.address }}</p>
                                    <p>Call us: {{ shop.contact }}</p>
                                </div>

                                <div class="visit-shop-btn">
                                    <a href="{% url 'core:visit_shop' shop.shopId %}" class="btn"> Visit Store</a>
                                </div>

                            </div>

                        {% endfor %}
                    </div>

            {% else %}
                <p>No shops yet. Please come back letter. </p>
            {% endif %}

        </div>
    </div>
</section>
{% endblock %}