bizlink/bizlink/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("core/", include("core.urls")),
    path("userauth/", include("userauth.urls")),
    path("chat/", include("chat.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

bizlink/chat/urls.py
from django.urls import path

from . import views

app_name = "chat"

urlpatterns = [
    path("", views.chat, name="chat"),
    path("chatroom/<chatGroupId>/", views.chatroom, name="chatroom"),
    path("get_or_create_chatroom/<username>/", views.get_or_create_chatroom, name="get_or_create_chatroom"),
    path('unread-count/<chatGroupId>/', views.unread_message_count, name='unread_message_count'),
]

bizlink/core/urls.py
from django.urls import path

from . import views

app_name = "core"

urlpatterns = [

    # Path for both

    ## Account
    path("account/", views.account, name="account"),
    path("account/notification/", views.notification, name="notification"),
    
    ## Wishlist
    path("wishlist/", views.wishlist, name="wishlist"),

    # Path for the owner

    ## Admin
    path("owner/home/admin/", views.admin, name="admin"),
    path("owner/home/admin/update_shop/", views.update_shop, name="update_shop"),
    path("owner/home/admin/create_feature/", views.create_feature, name="create_feature"),
    path('owner/home/admin/add_featured_product/', views.add_featured_product, name='add_featured_product'),
    path('owner/home/admin/delete_featured_product/', views.delete_featured_product, name="delete_featured_product"),
    path('owner/home/admin/add_new_arrival/', views.add_new_arrival, name='add_new_arrival'),
    path('owner/home/admin/delete_new_arrival/', views.delete_new_arrival, name="delete_new_arrival"),
    path('owner/home/admin/delete_feature/', views.delete_feature, name="delete_feature"),

    ## Category
    path("owner/home/categories/", views.category, name="category"),
    path("owner/home/category/<categoryId>/", views.category_detail, name="category_detail"),

    ## Product
    path("owner/home/products/", views.product, name="product"),
    path("owner/home/product/<productId>/", views.product_detail, name="product_detail"),
    path('owner/home/product/apply-discount/<productId>/', views.apply_discount, name='apply_discount'),
    path('owner/home/product/delete-discount/<productId>/', views.delete_discount, name='delete_discount'),
    path("owner/home/products/tag/<slug:tag_slug>/", views.tag, name="tag"),

    ## Factory
    path("owner/factory/", views.factory, name="factory"),
    path("owner/home/inventory/get_updated_stock/", views.get_updated_stock, name="get_updated_stock"),

    ## Inventory
    path("owner/home/inventory/", views.inventory, name="inventory"),
    path("owner/home/inventory/delete_product/", views.delete_product, name="delete_product"),
    path("owner/home/inventory/add_stock/", views.add_stock, name="add_stock"),
    path("owner/home/inventory/sell_stock/", views.sell_stock, name="sell_stock"),
    path("owner/home/inventory/undo_last_transaction/", views.undo_last_transaction, name="undo_last_transaction"),
    path("owner/home/inventory/delete_category/", views.delete_category, name="delete_category"),
    path("owner/home/inventory/delete_transaction_log/", views.delete_transaction_log, name="delete_transaction_log"),
    path("owner/home/inventory/delete_more_product_image/", views.delete_more_product_image, name="delete_more_product_image"),
    path("owner/home/inventory/delete_more_product_video/", views.delete_more_product_video, name="delete_more_product_video"),
    path("owner/home/inventory/delete_product_video/", views.delete_product_video, name="delete_product_video"),
    path("owner/home/inventory/update_product_info/<productId>", views.update_product_info, name="update_product_info"),
    path("owner/home/inventory/category_inventory_view/<categoryId>/", views.category_inventory_view, name="category_inventory_view"),
    path("owner/home/inventory/update_category_info/<categoryId>", views.update_category_info, name="update_category_info"),
    path("owner/home/inventory/delete_category_image/", views.delete_category_image, name="delete_category_image"),

    ## Search
    path("owner/home/search/", views.search_owner, name="search_owner"),
    path("owner/home/search/filter_searched_product/", views.filter_searched_product, name="filter_searched_product"),

    ## Shop
    path("owner/shop/", views.owner_shop, name="owner_shop"),
    path("owner/shop/add-to-wishlist/", views.add_to_wishlist, name="add-to-wishlist"),

    # Path for the Customer Pages
    
    path("customer/home/", views.customer_home, name="customer_home"),
    path("customer/shop/", views.shop_collection, name="shop_collection"),
    path("customer/home/shops/search", views.search_customer, name="search_customer"),
    path("customer/shops/visit_shop/<shopId>/", views.visit_shop, name="visit_shop"),
]

bizlink/userauth/urls.py
from django.urls import path
from . import views

app_name = "userauth"

urlpatterns = [
    path("signup/", views.signup, name="signup"),
    path("user_login/", views.user_login, name="user_login"),
    path("user_logout/", views.user_logout, name="user_logout"),
    path("edit_profile/", views.edit_profile, name="edit_profile"),
    path('manage_social_media/', views.manage_social_media, name='manage_social_media'),
]

bizlink/core/models.py
from django.db import models

# Create your models here.

bizlink/shop/models.py
from django.db import models
from django.conf import settings
from shortuuid.django_fields import ShortUUIDField
from django.utils.html import mark_safe
from taggit.managers import TaggableManager
from django.db.models import Sum

# Creating Status Choices for Products
STATUS_CHOICES = (
        ('processing', 'Processing'),
        ('shipped', 'Shipped'),
        ('delivered', 'Delivered'),
)

# Creating Rating for Products and Shops
RATING = (
        (1, '★☆☆☆☆'),
        (2, '★★☆☆☆'),
        (3, '★★★☆☆'),
        (4, '★★★★☆'),
        (5, '★★★★★'),
)

# Creating Status for Products
STATUS = (
        ('draft', 'Draft'),
        ('disabled', 'Disabled'),
        ('rejected', 'Rejected'),
        ('in_review', 'In Review'),
        ('published', 'Published'),
)

# Custom file upload path for shop images
def shop_directory_path(instance, filename):
    return 'user_{0}/shop_{1}/{2}'.format(instance.created_by.id, instance.shopId, filename)

# Custom file upload path for category images
def category_directory_path(instance, filename):
    return 'user_{0}/shop_{1}/category_{2}/{3}'.format(
        instance.created_by.id, instance.shop.shopId, instance.categoryId, filename
    )

# Custom file upload path for product images
def product_directory_path(instance, filename):
    return 'user_{0}/shop_{1}/category_{2}/product_{3}/{4}'.format(
        instance.created_by.id, instance.shop.shopId, instance.category.categoryId, instance.productId, filename
    )

# Custom file upload path for product videos
def product_video_directory_path(instance, filename):
    return 'user_{0}/shop_{1}/category_{2}/product_{3}/videos/{4}'.format(
        instance.created_by.id, instance.shop.shopId, instance.category.categoryId, instance.productId, filename
    )


# Custom file upload path for more product images
def mpi_directory_path(instance, filename):
    return 'user_{0}/shop_{1}/category_{2}/product_{3}/more_images/{4}'.format(
        instance.product.created_by.id, instance.product.shop.shopId, instance.product.category.categoryId, instance.product.productId, filename
    )

# Custom file upload path for more product videos
def mpv_directory_path(instance, filename):
    return 'user_{0}/shop_{1}/category_{2}/product_{3}/more_videos/{4}'.format(
        instance.product.created_by.id, instance.product.shop.shopId, instance.product.category.categoryId, instance.product.productId, filename
    )

# Custom file upload path for feature images
def feature_directory_path(instance, filename):
    return 'user_{0}/shop_{1}/feature_{2}/{3}'.format(
        instance.shop.created_by.id, instance.shop.shopId, instance.featureId, filename
    )

# Create your models here.
class Tag(models.Model):
    pass

class ProductVideo(models.Model):
    created_by = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='user_videos', on_delete=models.CASCADE)
    description = models.TextField(blank=True, null=True)
    video = models.FileField(upload_to='product_video_directory_path', null=True, blank=True)

    class Meta:
        verbose_name_plural = "Product Videos"
    
    def __str__(self):
        return str(self.video)

class Shop(models.Model):
    shopId = ShortUUIDField(unique=True, length=10, max_length=21, prefix="shop", alphabet="ABCDEF0123456789")

    name = models.CharField(max_length=255)
    description = models.TextField(blank=False, null=False)
    image = models.ImageField(upload_to='shop_directory_path', blank=True, null=True)

    address = models.TextField(blank=False, null=False)
    contact = models.CharField(max_length=255)

    created_at = models.DateTimeField(auto_now_add=True)
    created_by = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="user_shop")

    class Meta:
        ordering = ('name',)
        unique_together = ('created_by', 'name')
    
    def __str__(self):
        return self.name
    
    def shop_image(self):
        if self.image and hasattr(self.image, 'url'):
            return mark_safe(f'<img src="{self.image.url}" width="50" height="50" />')
        else:
            # Return a placeholder or default image
            return "No Image Available"

class Category(models.Model):
    categoryId =  ShortUUIDField(unique=True, length=10, max_length=21, prefix="category", alphabet="ABCDEF0123456789")

    name = models.CharField(max_length=255)
    description = models.TextField(blank=False, null=False)
    image = models.ImageField(upload_to='category_directory_path', blank=True, null=True)
    shop = models.ForeignKey(Shop, related_name='shop_categories', on_delete=models.CASCADE)

    created_at = models.DateTimeField(auto_now_add=True)
    created_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="user_categories")

    class Meta:
        ordering = ('name',)
        verbose_name_plural = 'Categories'
        unique_together = ('created_by', 'name')
    
    def __str__(self):
        return self.name
    
    def category_image(self):
        if self.image:
            return mark_safe('<img src="%s" width="50" height="50"/>' %(self.image.url))
        return ""
    
    def total_value(self):
        return self.category_products.aggregate(total=Sum('price'))['total'] or 0.00

class Product(models.Model):
    productId =  ShortUUIDField(unique=True, length=10, max_length=21, prefix="product", alphabet="ABCDEF0123456789")

    name = models.CharField(max_length=255)
    category = models.ForeignKey(Category, related_name='category_products', on_delete=models.CASCADE)
    image = models.ImageField(upload_to='product_directory_path', blank=True, null=True)
    video = models.ForeignKey(ProductVideo, null=True, blank=True, on_delete=models.SET_NULL, related_name="product_on_the_video")

    shop = models.ForeignKey(Shop, related_name='shop_products', on_delete=models.CASCADE)

    description = models.TextField(blank=True, null=True)
    specifications = models.TextField(blank=True, null=True)
    
    mfg = models.DateTimeField(auto_now_add=False, null=True, blank=True)  

    price = models.DecimalField(max_digits=15, decimal_places=2)

    stock_quantity = models.PositiveIntegerField()

    created_by = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='user_products', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    tags = TaggableManager(blank=True)

    sku = ShortUUIDField(unique=True, length=4, max_length=10, prefix="sku", alphabet="0123456789")

    class Meta:
        ordering = ('name',)
        unique_together = ('created_by', 'name', 'category')
    
    def __str__(self):
        return self.name
    
    def product_image(self):
        return mark_safe('<img src="%s" width="50" height="50"/>' %(self.image.url))
    
    def check_stock_status(self):
        if self.stock_quantity > 0:
            return "In Stock"
        else:
            return "Out of Stock"
    
    def get_mfg_display(self):
        if self.mfg:
            return self.mfg
        return "Not Specified"
    
class DiscountedProduct(models.Model):
    discountProductId = ShortUUIDField(unique=True, length=10, max_length=27, prefix="discountedProduct", alphabet="ABCDEF0123456789")

    shop = models.ForeignKey(Shop, related_name='shop_discounted_products', on_delete=models.CASCADE)

    product = models.OneToOneField(Product, on_delete=models.CASCADE, related_name='discounted_product')
    new_price = models.DecimalField(max_digits=15, decimal_places=2)
    discount_until = models.DateTimeField(null=True, blank=True) 
    has_discount_ended = models.BooleanField(default=False)

    created_by = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='user_discounted_products', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('product__name',)
        verbose_name_plural = "Discounted Products"
        unique_together = ('shop', 'product')
    
    def __str__(self):
        return self.product.name
    
    def discounted_product_image(self):
        return mark_safe('<img src="%s" width="50" height="50"/>' %(self.product.image.url))
    
    def product_name(self):
        return self.product.name

    def product_price(self):
        return self.product.price
    
    def get_percentage(self):
        if self.new_price > 0:
            discount = 100 - ((self.new_price / self.product.price) * 100)
            return discount
        return 0

class MoreProductImage(models.Model):
    mpiId = ShortUUIDField(unique=True, length=10, max_length=21, prefix="mpi", alphabet="ABCDEF0123456789")

    image = models.ImageField(upload_to='mpi_directory_path', blank=True, null=True)
    product = models.ForeignKey(Product, related_name='more_product_images', on_delete=models.CASCADE)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name_plural = "More Product Images"
    
    def __str__(self):
        return str(self.image)
    
    def more_product_image(self):
        return mark_safe('<img src="%s" width="50" height="50"/>' %(self.image.url))

class MoreProductVideo(models.Model):
    mpvId = ShortUUIDField(unique=True, length=10, max_length=21, prefix="mpv", alphabet="ABCDEF0123456789")

    video = models.FileField(upload_to='mpv_directory_path', null=True, blank=True)
    description = models.TextField(blank=True, null=True)

    product = models.ForeignKey(Product, related_name='more_product_videos', on_delete=models.CASCADE)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name_plural = "More Product Videos"
    
    def __str__(self):
        return str(self.video)
    
    def more_product_video(self):
        if self.video:

bizlink/shop/views.py
from django.shortcuts import render

# Create your views here.

bizlink/templates/core/owner/filtered-product.html
<div class="product-collection" id="filtered-product">
    {% if products %}
        <h3>
            {% if products.count == 1 %}
                1 Product
            {% else %}
                {{ products.count }} Products
            {% endif %}
        </h3>
        <div class="product-collection-box">
            {% for product in products %}
                <div class="product-box">
                    <a href="{% url 'core:product_detail' product.productId %}">
                        <div class="product-image">
                            <img src="{{ product.image.url }}" alt="{{ product.name }} image">
                        </div>
                    </a>
                    <p>{{ product.category.name }}</p>
                    <h4>{{ product.name }}</h4>
                    <p>By {{ product.shop.name }}</p>
                    <div class="price-and-button">
                        <p class="price">${{ product.price }}</p>
                    </div>
                </div>
            {% endfor %}
        </div>
    {% else %}
        <p>No products available. <a href="#">Click here</a> to create products</p>
    {% endif %}
</div>

bizlink/templates/core/owner/owner-base.html
{% extends "core/base.html" %}

{% load static %}

<!-- Owner Submenu Section -->
{% block submenu %}

<section class="owner_submenu_section">
    <div class="container">
        <div class="owner-submenu-section-box">
            <ul class="submenu">
                <li><a href="{% url 'core:owner_shop' %}">Shop</a></li>
                <li><a href="{% url 'core:product' %}">Products</a></li>
                <li><a href="{% url 'core:category' %}">Categories</a></li>
                {% if user.user_type == 'business_owner' %}
                    <li><a href="{% url 'core:admin' %}">Admin</a></li>
                    <li><a href="{% url 'core:inventory' %}">Inventory</a></li>
                    <li><a href="{% url 'core:factory' %}">Factory</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
</section>

{% endblock %}

<!-- Space to Display Error & Success Messages -->

{% block message %}

<section class="owner_submenu_message_box_section">

  {% if messages %}
    {% for message in messages %}

      <div class="alert alert-dismissible message-box fade show 
        {% if 'error' in message.tags %}alert-danger{% endif %}
        {% if 'success' in message.tags %}alert-success{% endif %}
        {% if 'info' in message.tags %}alert-info{% endif %}
        " role="alert">
          <strong>{{ message }}</strong>
          <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>

    {% endfor %}
  {% endif %}

</section>


{% endblock %}

bizlink/templates/core/owner/product.html
{% extends "core/owner/owner-base.html" %}

{% load static %}

{% block title %}
Products
{% endblock %}

{% block content %}

<!-- Product Intro Section -->
<section class="product_intro_section">
    <div class="container">
        <div class="intro-section-box">
            <div class="intro-banner">
                <h3>Products</h3>

                <div class="breadcrumb-box">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="{% url 'core:owner_shop' %}">Shop</a></li>
                        <li class="breadcrumb-item active" aria-current="page">Products</li>
                      </ol>
                </div>

            </div>

            <!-- Filtering -->
            <div class="container">
                <div class="filter-box">
                
                    {% if products %}
                        {% if categories %}
            
                            <div class="filter-by-category">
                                
                                <a href="{% url 'core:category' %}">
                                    <h3>Category</h3>
                                </a>
                                
                                <div class="category-collection">
                                    {% for category in categories%}
                
                                        <div class="category-box">
                                            <label class="category-label">
                                                <input type="checkbox" class="category-checkbox filter-checkbox" data-filter="category" value="{{ category.categoryId}}">
                                                &nbsp;<p class="category-name">{{ category.name }}</p>
                                            </label>
                                        </div>                                                                    
                
                                    {% endfor %}
                                </div>
                            </div>

                            <div class="filter-by-price">
                                <h3>Filter by Price</h3>
                                <div class="price-filter-box">
                                    <div class="min-price">
                                        <label for="min-price-input">Min Price:</label>
                                        <input type="number" id="min-price-input" name="min-price" step="0.01" placeholder="Min Price">
                                        <p class="error" id="min-price-error">Minimum price cannot be greater than maximum price.</p>
                                        <div class="error" id="negative-min-error">Minimum price cannot be negative.</div>
                                    </div>
                                    
                                    <div class="max-price">
                                        <label for="max-price-input">Max Price:</label>
                                        <input type="number" id="max-price-input" name="max-price" step="0.01" placeholder="Max Price">
                                        <div class="error" id="max-price-error">Maximum price cannot be negative.</div>
                                    </div>                                    
                                </div>
                            </div>                            

                        {% endif %}
                    {% endif %}
                </div>
            </div>

            <div class="product-collection" id="filtered-product">
                {% if products %}

                    <h3>

                        {% if products.count  == 1 %}
                            1 Product
                        {% else %}
                            {% if products.count == 0 %}
                                <p>You have no products</p>
                            {% else %}
                                {{ products.count }} Products
                            {% endif %}
                        {% endif %}

                    </h3>
                        
                        <div class="product-collection-box">

                            {% for product in products %}

                                <div class="product-box">
                                
                                    <a href="{% url 'core:product_detail' product.productId %}">
                                        <div class="product-image">
                                            <img src="{{ product.image.url }}" alt="{{ product.name }} image">
                                        </div>
                                    </a>

                                    <a href="#" class="add-to-wishlist" data-product-item="{{ product.productId }}">
                                        <i class="fa-solid fa-heart {% if product.productId in wishlist_items %}green-heart{% endif %}">
                                        </i>
                                    </a>

                                    <p>{{ product.category.name }}</p>
                                    <h4>{{ product.name }}</h4>
                                    <p>By {{ product.shop.name }}</p>

                                    <div class="price-and-button">
                                        <p class="price">${{ product.price }}</p>
                                    </div>

                                </div>

                            {% endfor %}
                        </div>

                {% else %}
                    <p>No products available.
                        {% if user.user_type == "business_owner" %}
                            <a href="{% url 'core:factory' %}">Click here</a> to create products</p>
                        {% endif %}
                {% endif %}
            </div>
        </div>
    </div>
</section>

<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="{% static 'js/custom-scripts/owner/search.js' %}"></script>  

{% endblock %}

bizlink/templates/core/owner/search.html
{% extends "core/owner/owner-base.html" %}

{% load static %}

{% block title %}
Search
{% endblock %}

{% block content %}

<!-- Search Result Section -->

<section class="search_result_section">
    <div class="container">

        <div class="result-section-box">

            <div class="intro-banner">
                {% if products %}

                <h3>{{ query|truncatechars:30 }}</h3>

                {% else %}

                <h4>Oops! Search Again</h4>

                {% endif %}

                <div class="breadcrumb-box">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="{% url 'core:owner_shop' %}">Shop</a></li>
                        <li class="breadcrumb-item"><a href="{% url 'core:product' %}">Products</a></li>
                        <li class="breadcrumb-item active" aria-current="page">{{ query|truncatechars:30 }}</li>
                      </ol>
                </div>

            </div>

            <!-- Filtering -->
            <div class="container">
                <div class="filter-box">
                
                    {% if products %}
                        {% if categories %}
            
                            <div class="filter-by-category">
                                
                                <a href="{% url 'core:category' %}">
                                    <h3>Category</h3>
                                </a>
                                
                                <div class="category-collection">
                                    {% for category in categories%}
                
                                        <div class="category-box">
                                            <label class="category-label">
                                                <input type="checkbox" class="category-checkbox filter-checkbox" data-filter="category" value="{{ category.categoryId}}">
                                                &nbsp;<p class="category-name">{{ category.name }}</p>
                                            </label>
                                        </div>                                                                    
                
                                    {% endfor %}
                                </div>
                            </div>

                            <div class="filter-by-price">
                                <h3>Filter by Price</h3>
                                <div class="price-filter-box">
                                    <div class="min-price">
                                        <label for="min-price-input">Min Price:</label>
                                        <input type="number" id="min-price-input" name="min-price" step="0.01" placeholder="Min Price">
                                        <p class="error" id="min-price-error">Minimum price cannot be greater than maximum price.</p>
                                        <div class="error" id="negative-min-error">Minimum price cannot be negative.</div>
                                    </div>
                                    
                                    <div class="max-price">
                                        <label for="max-price-input">Max Price:</label>
                                        <input type="number" id="max-price-input" name="max-price" step="0.01" placeholder="Max Price">
                                        <div class="error" id="max-price-error">Maximum price cannot be negative.</div>
                                    </div>                                    
                                </div>
                            </div>                            

                        {% endif %}
                    {% endif %}
                </div>
            </div>

            <div class="product-collection" id="filtered-product">
                {% if products %}

                    <h3>

                        {% if products.count  == 1 %}
                            1 Product
                        {% else %}
                            {% if products.count == 0 %}
                                <p>You have no products</p>
                            {% else %}
                                {{ products.count }} Products
                            {% endif %}
                        {% endif %}

                    </h3>
                        
                        <div class="product-collection-box">

                            {% for product in products %}

                                <div class="product-box">
                                
                                    <a href="{% url 'core:product_detail' product.productId %}">
                                        <div class="product-image">
                                            <img src="{{ product.image.url }}" alt="{{ product.name }} image">
                                        </div>
                                    </a>

                                    <p>{{ product.category.name }}</p>
                                    <h4>{{ product.name }}</h4>
                                    <p>By {{ product.shop.name }}</p>

                                    <div class="price-and-button">
                                        <p class="price">${{ product.price }}</p>
                                    </div>

                                </div>

                            {% endfor %}
                        </div>

                {% else %}
                    <p>No products available. <a href="#">Click here</a> to create products</p>
                {% endif %}
            </div>
        </div>
    </div>
</section>
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="{% static 'js/custom-scripts/owner/search.js' %}"></script>  

{% endblock %}